FROM gradle:jdk8 AS build
WORKDIR /app
COPY --chown=gradle:gradle . .
RUN gradle war --no-daemon

FROM tomcat:9.0-jre8-openjdk
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build /app/build/libs/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]